version: '3.4'

services:
  dummyservice.app:
    image: iqan/dummyserviceapp
    build:
      context: .
      dockerfile: DummyService.App/Dockerfile
    environment:
      - EndpointConfiguration:ConnectionString=<your-servicebus-connectionstring>
      - EndpointConfiguration:Topic=<your-topic-name>
      - EndpointConfiguration:Subscription=<your-subscription-name>
      - ConnectionStrings:<your-db-connectionstring>
    depends_on:
      - db
  db: 
    image: "iqan/dummydatabase"
    build:
      context: .
      dockerfile: DummyDatabase/Dockerfile
    environment:
      - SA_PASSWORD=SuperSecretPassword#1
      - ACCEPT_EULA=Y
  dummyservice.tests:
    image: iqan/dummyservicetests
    build:
      context: .
      dockerfile: DummyService.AcceptanceTests/Dockerfile
    environment:
      - EndpointConfiguration:ConnectionString=<your-servicebus-connectionstring>
      - EndpointConfiguration:Topic=<your-topic-name>
      - EndpointConfiguration:Subscription=<your-subscription-name>
      - ConnectionStrings:<your-db-connectionstring>
    depends_on:
      - db
      - dummyservice.app
    command: ["./wait-for-it.sh", "db:1433", "-t", "30", "--", "dotnet", "test", "DummyService.AcceptanceTests.csproj"]